version: "3.8"
services:
  coffeehouse-server:
    build:
      context: ./
      dockerfile: applications/coffeehouse-server/Dockerfile
    depends_on:
      - h2database
    deploy:
      replicas: 2
    env_file:
      - .env    
    links:
      - h2database
    networks:
      - coffeehouse
  h2database:
    image: oscarfonts/h2:latest
    environment:
      H2_OPTIONS: -ifNotExists
    networks:
      - coffeehouse
    ports:
      - "50081:81"
    volumes:
      - ./.docker/h2database:/opt/h2-data
  nginx:
    image: nginx:stable-alpine3.17
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.tmpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    env_file:
      - .env
    networks:
      - coffeehouse
    ports:
      - "50080:80"
    volumes:
      - ./.env-nginx.conf.tmpl:/etc/nginx/conf.d/nginx.conf.tmpl
networks:
  coffeehouse:
