coffeehouse:
  order:
    server-uri: http://${COFFEEHOUSE_SERVER_HOST:localhost}:${COFFEEHOUSE_SERVER_PORT:9080}

modulemesh:
  event:
    rabbit:
      default-exchange: amq.fanout
      queue-names: coffeehouse-event-stream.brew-server

spring:
  rabbitmq:
    connection-timeout: 10

server:
  port: ${COFFEEHOUSE_BREW_SERVER_PORT:9040}

logging:
  group:
    application: coffeehouse.applications
    module: coffeehouse.modules
    library: coffeehouse.libraries
