coffeehouse:
  user:
    server-uri: http://${COFFEEHOUSE_SERVER_HOST:localhost}:${COFFEEHOUSE_SERVER_PORT:9080} 

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - name: JSONWebTokenRelay          
      routes:
        - id: coffeehouse-server
          uri: http://${COFFEEHOUSE_SERVER_HOST:localhost}:${COFFEEHOUSE_SERVER_PORT:9080}
          predicates:
            - Path=/**
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: ${COFFEEHOUSE_EDGE_SERVER_PORT:8080}

logging:
  group:
    application: coffeehouse.applications
    library: coffeehouse.libraries
