server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

logging:
  level:
    application: DEBUG
    module: DEBUG
    library: DEBUG
    web: DEBUG
    sql: DEBUG
