spring:
  integration:
    jdbc:
      initialize-schema: always

server:
  port: ${COFFEEHOUSE_SERVER_PORT:8080} 

logging:
  group:
    application: coffeehouse.applications
    module: coffeehouse.modules
    library: coffeehouse.libraries
  level:
    application: DEBUG
    module: DEBUG
    library: DEBUG
    web: DEBUG
    sql: DEBUG
