spring:
  integration:
    jdbc:
      initialize-schema: always

server:
  port: ${COFFEEHOUSE_SERVER_PORT:9080} 

logging:
  group:
    application: coffeehouse.applications
    module: coffeehouse.modules
    library: coffeehouse.libraries
