server:
  port: ${COFFEEHOUSE_SERVER_PORT:8080} 

logging:
  group:
    application: coffeehouse.applications
    library: coffeehouse.libraries
  level:
    application: DEBUG
    library: DEBUG
    web: DEBUG
    sql: DEBUG
